### ISSUE TITLE
Fix startOf function for isoWeek

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-adapter-date-fns#22]
The startOf function is accepting a boolean for Sunday(false) and Monday(true).

Instead it should get the the week day (number) between 0 (Sunday) and 6(Saturday) in order to be more flexible to provide the startOf the week based on the parameter.

See https://github.com/chartjs/chartjs-adapter-luxon/issues/23

**Comment by kurkle** [comment]
It already works as expected.
