### ISSUE TITLE
Will you update NPM?

### ISSUE THREAD

**Issue by Yahav** [chartjs/chartjs-adapter-date-fns#26]
Currently migrating to Chart.js v3-beta and it seem like both latest/next versions at NPM doesn't contain #16 .
Without this commit the adapter doesn't work at all with v3. 
Is it possible to update NPM version or at least update the "latest" version there?

**Comment by mschlitz-trux** [comment]
`chart-js-adapter-date-fns@next` seems to work, but you can also specify versions.

E.g.
```
"chartjs-adapter-date-fns": "^1.1.0-alpha.3",
"chartjs-plugin-annotation": "^0.5.7",
```

**Comment by Drumstix42** [comment]
Specifying `chartjs-adapter-date-fns@next` seems to work. Or you can specify versions:
```
"chart.js": "3.0.0-beta.7",
"chartjs-adapter-date-fns": "^1.1.0-alpha.3",
```
