### ISSUE TITLE
Add cdnjs link in readme

### ISSUE THREAD

**Issue by tamalchowdhury** [chartjs/chartjs-adapter-date-fns#53]
I just added chartjs date fns to cdnjs. Would you like me to change the links shown in the readme.md to the cdnjs version? Thanks

**Comment by kurkle** [comment]
Does it work in China already? I think its the main reason why we have jsdelivr links (+ jsdelivr.com uses Chart.js)

**Comment by tamalchowdhury** [comment]
I am not sure about that. So I am closing this issue right now. Thanks a lot.
